// <auto-generated />
using System;
using CalendarioMantenimientoPreventivo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalendarioMantenimientoPreventivo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222161704_AddNotificaciones")]
    partial class AddNotificaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("CalendarioMantenimientoPreventivo.Models.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locales");
                });

            modelBuilder.Entity("CalendarioMantenimientoPreventivo.Models.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Dia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("CalendarioMantenimientoPreventivo.Models.MantenimientoNotificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaMostrada")
                        .HasColumnType("TEXT");

                    b.Property<int>("MantenimientoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MantenimientoId", "Tipo")
                        .IsUnique();

                    b.ToTable("MantenimientoNotificaciones");
                });

            modelBuilder.Entity("CalendarioMantenimientoPreventivo.Models.ParametroSistema", b =>
                {
                    b.Property<string>("Clave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Clave");

                    b.ToTable("ParametrosSistema");
                });

            modelBuilder.Entity("CalendarioMantenimientoPreventivo.Models.Mantenimiento", b =>
                {
                    b.HasOne("CalendarioMantenimientoPreventivo.Models.Local", "Local")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");
                });

            modelBuilder.Entity("CalendarioMantenimientoPreventivo.Models.MantenimientoNotificacion", b =>
                {
                    b.HasOne("CalendarioMantenimientoPreventivo.Models.Mantenimiento", "Mantenimiento")
                        .WithMany("Notificaciones")
                        .HasForeignKey("MantenimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mantenimiento");
                });

            modelBuilder.Entity("CalendarioMantenimientoPreventivo.Models.Local", b =>
                {
                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("CalendarioMantenimientoPreventivo.Models.Mantenimiento", b =>
                {
                    b.Navigation("Notificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
